---
abstract: 'A POE component that implements an RFC 862 Echo server.'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.89'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-Server-Echo
no_index:
  directory:
    - examples
    - inc
    - t
provides:
  POE::Component::Server::Echo:
    file: lib/POE/Component/Server/Echo.pm
    version: 1.64
requires:
  POE: 0.38
  POE::Driver::SysRW: 0
  POE::Filter::Line: 0
  POE::Wheel::ReadWrite: 0
  POE::Wheel::SocketFactory: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/poe-component-server-echo/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-server-echo.git
version: 1.64
