author: 'Chris Williams <chris@bingosnet.co.uk>'
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
module_name: POE::Component::Server::Echo
name: POE-Component-Server-Echo
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  POE: 0.0607
  Socket: 0
version: 1.4
